import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { once } from 'node:events';
import { createApp } from '../src/server.js';
import { codexSample, codexTurn, claudeSample } from '../src/demo.js';
import { activationInfo } from '../src/activation.js';
import { nodeActivation } from '../src/node-activation.js';
import { claudeTitle } from '../src/claude-title.js';
import { parse } from '../src/transcript.js';
async function setup(t) {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'grove-node-activate-'));
    const app = createApp({ root: path.join(root, 'library'), roots: { codex: path.join(root, 'codex'), claude: path.join(root, 'claude') }, guard: () => {} });
    app.server.listen(0, '127.0.0.1'); await once(app.server, 'listening');
    t.after(async () => { await new Promise(r => app.close(r)); fs.rmSync(root, { recursive: true, force: true }); });
    const api = async (route, body, method = 'POST') => { const response = await fetch('http://127.0.0.1:' + app.server.address().port + '/api/' + route, { method, headers: { 'X-Grove-Token': app.token, 'Content-Type': 'application/json' }, ...(body ? { body: JSON.stringify(body) } : {}) }); return { status: response.status, value: await response.json() }; };
    return { app, root, api };
}
test('activate an internal node includes it, preserves suffixes, labels native title, and attaches new work', async t => {
    const { app, root, api } = await setup(t), store = app.store;
    const b = store.branch(null, 'My session', 'codex', codexSample(root, [['Setup', 'Ready'], ['Existing later question', 'Long later answer. '.repeat(100)]]));
    let graph = store.treeGraph(b.id);
    store.organize(b.id, { version: graph.version, pathId: b.id, chatIds: graph.paths[0].messages.slice(0, 2).map(m => m.id), action: 'combine', name: 'Setup node' });
    graph = store.treeGraph(b.id); const sourceRaw = store.raw(b.head), node = graph.nodes.find(n => n.name === 'Setup node');
    const target = { branchId: b.id, nodeId: node.id, version: graph.version, cwd: root };
    const preview = (await api('node-activation/check', target)).value;
    assert.equal(preview.title, '[Grove] My session · Setup node'); assert.equal(preview.complete, true);
    assert.ok(preview.estimated < activationInfo(store, app.native, b.id, root).estimated);
    assert.equal(store.all('branch').length, 1, 'preview creates no branch');
    assert.equal((await api('node-activation/activate', { ...target, contextAcknowledgement: 'stale' })).status, 409);
    const response = await api('node-activation/activate', { ...target, contextAcknowledgement: preview.fingerprint }); assert.equal(response.status, 201);
    const child = response.value.branch, instance = store.instances().find(i => i.branchId === child.id && i.applied);
    assert.equal(child.parentId, b.id); assert.equal(instance.title, preview.title);
    assert.equal(store.detail(child.id).messages.length, 2); assert.equal(store.raw(b.head), sourceRaw);
    const index = fs.readFileSync(path.join(root, 'codex', 'session_index.jsonl'), 'utf8'); assert.ok(index.includes(preview.title));
    graph = store.treeGraph(b.id);
    store.organize(b.id, { version: graph.version, pathId: child.id, nodeId: 'empty-' + child.id, action: 'rename', name: 'Next work' });
    assert.equal(store.treeGraph(b.id).nodes.find(n => n.id === 'empty-' + child.id).name, 'Next work');
    fs.appendFileSync(instance.file, codexTurn('New continuation', 'New response').map(v => JSON.stringify(v) + '\n').join(''));
    app.native.refreshLocal();
    assert.equal(store.get('branch', child.id).name, 'My session');
    graph = store.treeGraph(b.id); const route = graph.paths.find(p => p.branchId === child.id);
    assert.deepEqual(route.messages.map(m => m.text), ['Setup', 'Ready', 'New continuation', 'New response']);
    assert.equal(route.nodeIds[0], node.id); assert.equal(store.raw(store.get('branch', b.id).head), sourceRaw);
    assert.equal(graph.nodes.find(n => n.id === route.nodeIds.at(-1)).name, 'Next work');
    assert.equal((await api('trash', { branchIds: [b.id], nodeId: node.id, version: graph.version })).status, 409);
});
test('terminal activation reuses the path and Claude receives the exact title', async t => {
    const { app, root, api } = await setup(t), b = app.store.branch(null, 'Claude session', 'claude', claudeSample(root, [['Question', 'Answer']]));
    let graph = app.store.treeGraph(b.id);
    app.store.organize(b.id, { version: graph.version, pathId: b.id, nodeId: graph.nodes[0].id, action: 'rename', name: 'Final node' });
    graph = app.store.treeGraph(b.id); const target = { branchId: b.id, nodeId: graph.nodes[0].id, version: graph.version, cwd: root };
    const preview = (await api('node-activation/check', target)).value;
    const response = await api('node-activation/activate', { ...target, contextAcknowledgement: preview.fingerprint }); assert.equal(response.status, 201);
    assert.equal(response.value.branch.id, b.id); assert.equal(app.store.all('branch').length, 1);
    const instance = app.store.instances().find(i => i.branchId === b.id && i.applied);
    assert.equal(claudeTitle(parse(fs.readFileSync(instance.file, 'utf8'), 'claude').records).title, '[Grove] Claude session · Final node');
});
test('node previews reject stale selections and unfinished logical boundaries', async t => {
    const { app, root } = await setup(t), store = app.store, b = store.branch(null, 'Boundary', 'codex', codexSample(root, [['Question', 'Answer']]));
    let graph = store.treeGraph(b.id);
    store.organize(b.id, { version: graph.version, pathId: b.id, chatIds: [graph.paths[0].messages[0].id], action: 'combine', name: 'User message only' });
    graph = store.treeGraph(b.id);
    const target = { branchId: b.id, nodeId: graph.nodes[0].id, version: graph.version, cwd: root };
    assert.equal(nodeActivation(store, app.native, target).preview.readiness, 'node-boundary');
    store.edit(b.id, { name: 'Renamed' }); assert.throws(() => nodeActivation(store, app.native, target), /changed/);
});
test('Trash listing does not compute the library graph or cloud directory', async t => {
    const { app, api } = await setup(t);
    app.store.snapshot = app.autoSync.listing = app.autoSync.decorate = () => { throw Error('Full library traversal'); };
    const result = await api('trash', null, 'GET'); assert.equal(result.status, 200); assert.deepEqual(result.value, { trashEntries: [], trashNative: [] });
});
test('switching tools from an internal node converts only its prefix and previews the native title', async t => {
    const { app, root, api } = await setup(t), store = app.store;
    const b = store.branch(null, 'Portable session', 'codex', codexSample(root, [['Keep this prefix', 'Prefix answer'], ['EXCLUDED_SUFFIX', 'EXCLUDED_ANSWER']]));
    let graph = store.treeGraph(b.id);
    store.organize(b.id, { version: graph.version, pathId: b.id, action: 'combine', name: 'Portable node', chatIds: graph.paths[0].messages.slice(0, 2).map(m => m.id) });
    graph = store.treeGraph(b.id);
    const options = { branchId: b.id, nodeId: graph.nodes[0].id, version: graph.version, cwd: root, target: 'claude', mode: 'messages' };
    const preview = (await api('conversion-check', options)).value;
    assert.equal(preview.title, '[Grove] Portable session · Portable node');
    const response = await api('convert', { ...options, fingerprint: preview.fingerprint, contextAcknowledgement: preview.budget.fingerprint });
    assert.equal(response.status, 201);
    const child = response.value.branch, raw = store.raw(child.head);
    assert.ok(raw.includes('Keep this prefix')); assert.ok(!raw.includes('EXCLUDED_SUFFIX'));
    assert.equal(store.instances().find(i => i.branchId === child.id && i.applied).title, preview.title);
});
