import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { Store } from '../src/store.js';
import { Native } from '../src/native.js';
import { AutoSync } from '../src/auto-sync.js';
import { codexSample, codexTurn } from '../src/demo.js';
function setup(t) {
    const root = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'grove-organize-')));
    const store = new Store(path.join(root, 'library')), cwd = path.join(root, 'work');
    const roots = { codex: path.join(root, 'codex'), claude: path.join(root, 'claude') };
    fs.mkdirSync(cwd);
    fs.mkdirSync(path.join(roots.codex, 'sessions'), { recursive: true });
    const native = new Native(store, { roots, guard: () => { } });
    t.after(() => { store.close(); fs.rmSync(root, { recursive: true, force: true }); });
    return { root, store, native, roots, cwd };
}
const append = pairs => pairs.flatMap(([u, a]) => codexTurn(u, a)).map(v => JSON.stringify(v) + '\n').join('');
const copy = (from, to) => to.merge(from.exportGraph(), Object.fromEntries(from.db.prepare('SELECT * FROM objects').all().map(o => [o.hash, o.body])));
test('20 new messages remain Pending, then commit as two named 10-message nodes without rewriting native data', t => {
    const { store, native, roots, cwd } = setup(t), project = store.project('Chrono');
    const raw = codexSample(cwd, [['Context', 'Ready']]);
    const branch = store.branch(project.id, 'Main', 'codex', raw);
    let detail = store.detail(branch.id);
    store.commitPending(branch.id, { name: 'Research context', end: detail.pending.checkpoints[0].end, revisionId: branch.head, expectedStart: 0 });
    native.setActive(branch.id, cwd, true);
    native.apply();
    const file = store.instances()[0].file;
    fs.appendFileSync(file, append(Array.from({ length: 10 }, (_, i) => [`Question ${i}`, `Answer ${i}`])));
    const nativeBefore = fs.readFileSync(file, 'utf8');
    native.refreshLocal();
    detail = store.detail(branch.id);
    assert.equal(detail.pending.count, 20);
    assert.equal(detail.nodes.length, 1);
    const boundary = detail.pending.checkpoints.find(c => c.messages === 10);
    const first = store.commitPending(branch.id, { name: 'Write Intro', end: boundary.end, revisionId: detail.head, expectedStart: detail.pending.start });
    detail = store.detail(branch.id);
    assert.equal(detail.pending.count, 10);
    assert.equal(detail.nodes.length, 2);
    const second = store.commitPending(branch.id, { name: 'Design experiments', end: detail.pending.checkpoints.at(-1).end, revisionId: detail.head, expectedStart: detail.pending.start });
    assert.equal(first.end, second.start);
    assert.equal(store.detail(branch.id).pending.count, 0);
    assert.equal(fs.readFileSync(file, 'utf8'), nativeBefore);
    native.refreshLocal();
    assert.equal(store.detail(branch.id).pending.count, 0);
    fs.appendFileSync(file, append([['One more task', 'Done']]));
    native.refreshLocal();
    assert.equal(store.detail(branch.id).pending.count, 2);
    assert.equal(store.detail(branch.id).nodes.length, 3);
});
test('stale or duplicate Pending commits fail without dropping records', t => {
    const { store, cwd } = setup(t), b = store.branch(null, 'Local', 'codex', codexSample(cwd, [['A', 'B'], ['C', 'D']]));
    const d = store.detail(b.id), options = { name: 'Part 1', end: d.checkpoints[0].end, revisionId: d.head, expectedStart: 0 };
    store.commitPending(b.id, options);
    assert.throws(() => store.commitPending(b.id, options), /already organized/);
    store.ingest(b.id, store.raw(d.head) + append([['E', 'F']]), d.head, {});
    assert.throws(() => store.commitPending(b.id, { ...options, expectedStart: options.end }), /Pending changed/);
    assert.equal(store.detail(b.id).pending.count, 4);
});
test('native local discovery preserves Active and groups three exact-prefix forks into one tree', t => {
    const { store, native, roots, cwd } = setup(t);
    for (let i = 0; i < 3; i++)
        fs.writeFileSync(path.join(roots.codex, 'sessions', `session-${i}.jsonl`), codexSample(cwd, [['Research', 'Context'], ['Shared constraints', 'Understood'], [`Direction ${i}`, `Outcome ${i}`]]));
    const result = native.refreshLocal();
    assert.equal(result.discovered, 3);
    const items = store.forest('local');
    assert.equal(items.length, 1);
    assert.equal(items[0].kind, 'tree');
    assert.equal(items[0].branchIds.length, 4);
    assert.equal(items[0].activeCount, 3);
    assert.equal(native.plan().operations.length, 0);
    native.refreshLocal();
    assert.equal(store.all('branch').length, 4);
    const p = store.project('Chrono');
    store.moveTree(items[0].id, p.id, 'Research');
    const projectItems = store.forest(p.id);
    assert.equal(projectItems.length, 1);
    assert.equal(projectItems[0].group, 'Research');
    assert.equal(projectItems[0].branchIds.length, 4);
    assert.equal(store.forest('local')[0].id, items[0].id);
});
test('matching titles or a short greeting do not merge unrelated sessions', t => {
    const { store, native, roots, cwd } = setup(t);
    fs.writeFileSync(path.join(roots.codex, 'sessions', 'a.jsonl'), codexSample(cwd, [['Hello', 'Hi'], ['Task A', 'Done A']]));
    fs.writeFileSync(path.join(roots.codex, 'sessions', 'b.jsonl'), codexSample(cwd, [['Hello', 'Hi'], ['Task B', 'Done B']]));
    native.refreshLocal();
    assert.equal(store.forest('local').length, 2);
    assert.ok(store.forest('local').every(i => i.kind === 'session'));
});
test('project collections contain standalone items and trees; logical commits alone do not make a tree', t => {
    const { store, cwd } = setup(t), p = store.project('Mixed'), b = store.branch(p.id, 'Notes', 'codex', codexSample(cwd, [['One', 'Done'], ['Two', 'Done']]));
    let d = store.detail(b.id);
    store.commitPending(b.id, { name: 'One', end: d.checkpoints[0].end, revisionId: d.head, expectedStart: 0 });
    d = store.detail(b.id);
    store.commitPending(b.id, { name: 'Two', end: d.checkpoints[1].end, revisionId: d.head, expectedStart: d.pending.start });
    assert.equal(store.forest(p.id)[0].kind, 'session');
    store.fork(b.id, { name: 'Explore', end: d.checkpoints[0].end });
    store.branch(p.id, 'Loose notes', 'codex');
    assert.deepEqual(store.forest(p.id).map(i => i.kind).sort(), ['session', 'tree']);
});
test('cloud exports only filed projects, including logical nodes; device Active never transfers', t => {
    const a = setup(t), b = setup(t), p = a.store.project('Cloud');
    const local = a.store.branch(null, 'Private local', 'codex', codexSample(a.cwd, [['Private local text', 'Not for cloud']]));
    const filed = a.store.branch(p.id, 'Filed', 'codex', codexSample(a.cwd, [['File me', 'Okay']]));
    const d = a.store.detail(filed.id);
    a.store.commitPending(filed.id, { name: 'Milestone', end: d.checkpoints[0].end, revisionId: d.head, expectedStart: 0 });
    const graph = a.store.exportGraph();
    assert.equal(graph.branches.length, 1);
    assert.equal(graph.nodes.length, 1);
    const bodies = graph.revisions.flatMap(r => r.refs).map(h => a.store.db.prepare('SELECT body FROM objects WHERE hash=?').get(h).body).join('');
    assert.ok(!bodies.includes('Private local text'));
    copy(a.store, b.store);
    assert.equal(b.store.detail(filed.id).nodes[0].name, 'Milestone');
    assert.equal(b.store.instances().length, 0);
    a.store.edit(filed.id, { name: 'Renamed' });
    copy(a.store, b.store);
    assert.equal(b.store.get('branch', filed.id).name, 'Renamed');
    assert.equal(b.store.local('conflicts').length, 0);
    a.store.moveTree(local.id, p.id, 'Misc');
    copy(a.store, b.store);
    assert.equal(b.store.forest(p.id).length, 2);
});
test('automatic upload queue survives lock and failures and only runs after an organization trigger', async t => {
    const { store, cwd } = setup(t), p = store.project('Queued'), b = store.branch(p.id, 'Main', 'codex', codexSample(cwd, [['Context', 'Ready']]));
    let attempts = 0;
    const auto = new AutoSync(store, () => ({ url: 'https://example.com/dav' }), async () => { attempts++; throw new Error('offline'); });
    t.after(() => auto.close());
    auto.schedule([b.id]); await auto.flush(); assert.equal(attempts, 0);
    auto.unlock('my-test-passphrase'); await assert.rejects(auto.flush(), /offline/);
    assert.equal(auto.status().phase, 'retrying'); assert.deepEqual(store.local('uploadQueue'), [b.id]);
    auto.lock(); assert.equal(auto.status().phase, 'locked');
});
test('concurrent logical organization preserves both partitions without displaying overlapping nodes', t => {
    const a = setup(t), b = setup(t), p = a.store.project('Shared');
    const branch = a.store.branch(p.id, 'Main', 'codex', codexSample(a.cwd, [['One', 'A'], ['Two', 'B']]));
    copy(a.store, b.store);
    const d = a.store.detail(branch.id);
    a.store.commitPending(branch.id, { name: 'First stage', end: d.checkpoints[0].end, revisionId: d.head, expectedStart: 0 });
    b.store.commitPending(branch.id, { name: 'One combined stage', end: d.checkpoints[1].end, revisionId: d.head, expectedStart: 0 });
    const merged = copy(a.store, b.store);
    assert.equal(merged.conflicts, 1);
    assert.equal(b.store.local('conflicts')[0].kind, 'organization');
    assert.equal(b.store.all('node').length, 2);
    assert.equal(b.store.detail(branch.id).nodes.length, 1);
    assert.equal(b.store.detail(branch.id).nodes[0].name, 'One combined stage');
    assert.equal(b.store.detail(branch.id).pending.count, 0);
});
test('sequential logical commits fast-forward across devices with the remaining Pending intact', t => {
    const a = setup(t), b = setup(t), p = a.store.project('Shared');
    const branch = a.store.branch(p.id, 'Main', 'codex', codexSample(a.cwd, [['One', 'A'], ['Two', 'B']]));
    let d = a.store.detail(branch.id);
    a.store.commitPending(branch.id, { name: 'Stage one', end: d.checkpoints[0].end, revisionId: d.head, expectedStart: 0 });
    copy(a.store, b.store);
    assert.equal(b.store.detail(branch.id).pending.count, 2);
    d = b.store.detail(branch.id);
    b.store.commitPending(branch.id, { name: 'Stage two', end: d.checkpoints[1].end, revisionId: d.head, expectedStart: d.pending.start });
    assert.equal(copy(b.store, a.store).conflicts, 0);
    assert.deepEqual(a.store.detail(branch.id).nodes.map(n => n.name), ['Stage one', 'Stage two']);
    assert.equal(a.store.detail(branch.id).pending.count, 0);
});
