// Synthetic end-to-end resource audit. Never reads personal native/cloud data.
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';import {once} from 'node:events';import {monitorEventLoopDelay} from 'node:perf_hooks';import assert from 'node:assert/strict';
import {Store} from '../src/store.js';import {Native} from '../src/native.js';import {AutoSync} from '../src/auto-sync.js';import {codexSample} from '../src/demo.js';import {hash} from '../src/util.js';import {INBOX_ID} from '../src/inbox.js';
const root=fs.mkdtempSync(path.join(os.tmpdir(),'grove-resource-audit-')),remote=new Map(),network={requests:0,methods:{},sent:0,received:0},phases=[];
const server=http.createServer(async(req,res)=>{network.requests++;network.methods[req.method]=(network.methods[req.method]||0)+1;const chunks=[];for await(const c of req){chunks.push(c);network.sent+=c.length;}const key=req.url,etag=remote.has(key)?'"'+hash(remote.get(key))+'"':null;const send=(status,body='')=>{network.received+=Buffer.byteLength(body);res.writeHead(status,etag?{ETag:etag}:{});res.end(body);};
 if(req.method==='MKCOL')return send(201);if(req.method==='PUT'){if(req.headers['if-none-match']==='*'&&remote.has(key))return send(412);remote.set(key,Buffer.concat(chunks));return send(201);}if(req.method==='PROPFIND')return send(207,'<d:multistatus xmlns:d="DAV:">'+[...remote.keys()].filter(k=>k.startsWith(key)&&!k.slice(key.length).includes('/')).map(k=>'<d:response><d:href>'+k+'</d:href></d:response>').join('')+'</d:multistatus>');if(!remote.has(key))return send(404);if(req.headers['if-none-match']===etag)return send(304);send(200,remote.get(key));});
server.listen(0,'127.0.0.1');await once(server,'listening');const config={url:'http://127.0.0.1:'+server.address().port+'/Session-Grove/',username:'fixture',password:'fixture'},key='synthetic-audit-key',a=new Store(path.join(root,'a')),b=new Store(path.join(root,'b')),autoA=new AutoSync(a,()=>config),autoB=new AutoSync(b,()=>config);autoA.unlock(key);autoB.unlock(key);
const roots={codex:path.join(root,'native/codex'),claude:path.join(root,'native/claude')};fs.mkdirSync(path.join(roots.codex,'sessions'),{recursive:true});const native=new Native(a,{roots,guard:()=>{}}),lag=monitorEventLoopDelay({resolution:10});lag.enable();
async function measure(name,fn){await new Promise(r=>setTimeout(r,12));lag.reset();const cpu=process.cpuUsage(),start=performance.now(),before={...network};await fn();await new Promise(r=>setImmediate(r));const memory=process.memoryUsage();phases.push({name,wallMs:Math.round(performance.now()-start),cpuMs:Math.round(Object.values(process.cpuUsage(cpu)).reduce((a,b)=>a+b,0)/1000),rssMiB:Math.round(memory.rss/1048576),heapMiB:Math.round(memory.heapUsed/1048576),requests:network.requests-before.requests,sentBytes:network.sent-before.sent,receivedBytes:network.received-before.received,eventLoopMaxMs:Math.round(lag.max/1e6)});}
try{
 for(let i=0;i<50;i++)fs.writeFileSync(path.join(roots.codex,'sessions',i+'.jsonl'),codexSample(root,Array.from({length:20},(_,j)=>['Question '+i+'/'+j,('Recorded answer '+i+'/'+j+' ').repeat(160)])));
 await measure('cold local discovery',()=>native.refreshLocal());const ids=a.syncCollections().items.map(i=>i.id);
 await measure('initial encrypted publication',()=>autoA.flush('push',true));
 await measure('new device directory only',async()=>{await autoB.flush('pull',true);await autoB.openProject(INBOX_ID);assert.equal(b.all('branch').length,0);});
 await measure('download one tree',()=>autoB.openTree(ids[0]));
 await measure('open and organize',()=>{const g=b.treeGraph(ids[0]);b.organize(ids[0],{version:g.version,pathId:g.paths[0].branchId,action:'combine',name:'Context',chatIds:g.paths[0].messages.slice(0,2).map(m=>m.id)});});
 await measure('publish layout-only change',()=>autoB.flush('push',true));
 await measure('pull and hydrate changed tree',async()=>{const plan=await autoA.prepareSync();autoA.startSync(plan.id,true);await autoA.syncJob;assert.ok(a.treeGraph(ids[0]).nodes.some(n=>n.name==='Context'));});
 const idleBefore=network.requests;await measure('200 unchanged local status/list cycles',()=>{for(let i=0;i<200;i++){autoA.status();a.snapshot();a.listing('projects');}});assert.equal(network.requests,idleBefore);
 await measure('warm capture',()=>native.refreshLocal());
 await measure('fork and native materialization',()=>{const p=a.detail(ids[0]),fork=a.fork(ids[0],{name:'Audit fork',end:p.checkpoints.at(-1).end});native.setActive(fork.id,root,true);native.apply([fork.id]);});
 const report={sessions:50,roundsPerSession:20,phases,network,peakRssKiB:process.resourceUsage().maxRSS,energy:'CPU, memory, network and event-loop measurements; no watt-hour claim.'};fs.mkdirSync('test-results',{recursive:true});fs.writeFileSync('test-results/performance-audit.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{lag.disable();autoA.close();autoB.close();a.close();b.close();server.close();await once(server,'close');fs.rmSync(root,{recursive:true,force:true});}
